### ISSUE TITLE
自动备份失败java.util.ConcurrentModificationException: Attempted to call MinecraftServer#saveAll async

### ISSUE THREAD

**Issue by 532763233** [QuickBackupMultiMod-Dev/QuickBackupM-Fabric#33]
### Bug description / Bug描述

自动备份时报错，备份失败

### Steps to reproduce / 复现步骤

等待自动备份

### Expected behavior / 预期行为

备份成功

### Actual behavior / 实际情况

`[03:00:00] [mongo-server-worker3/INFO]: client [id: 0x5ccce330, L:/127.0.0.1:40633 - R:/127.0.0.1:48812] connected
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: §a备份§r中...请稍等
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]: java.util.ConcurrentModificationException: Attempted to call MinecraftServer#saveAll async
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]:    at net.minecraft.server.MinecraftServer.handler$zzn000$c2me-fixes-general-threading-issues$preventAsyncSaveAll(MinecraftServer.java:12891)
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]:    at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java)
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]:    at dev.skydynamic.quickbackupmulti.utils.MakeUtils.make(MakeUtils.java:127)
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]:    at dev.skydynamic.quickbackupmulti.utils.MakeUtils.scheduleMake(MakeUtils.java:233)
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]:    at dev.skydynamic.quickbackupmulti.utils.schedule.ScheduleBackup.execute(ScheduleBackup.java:27)
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]:    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: [STDERR]:    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[03:00:00] [DefaultQuartzScheduler_Worker-1/ERROR]: java.util.ConcurrentModificationException: Attempted to call MinecraftServer#saveAll async
[03:00:00] [DefaultQuartzScheduler_Worker-1/INFO]: §a备份§r失败，错误原因java.util.ConcurrentModificationException: Attempted to call MinecraftServer#saveAll async
`
<img width="1568" alt="Snipaste_2024-06-14_09-44-29" src="https://github.com/SkyDynamic/QuickBackupM-Fabric/assets/62412476/96e5242a-509d-4f3d-bb02-5760c9421c47">

### Minecraft version / Minecraft版本

1.20.4

### Mod version / Mod版本

2.0.5

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by lzz934** [comment]
所以怎么解决？

**Comment by Zhaosn** [comment]
> 所以怎么解决？

https://github.com/QuickBackupMultiMod-Dev/QuickBackupM-Fabric/issues/40#issuecomment-2213067314
更新最新版
